arch = "HV 1.5"
_source_script = "3.7hv_1_5_train_lora.ps1"
dataset_config = "./toml/qinglong-hv-1-5-datasets.toml"
dit_path = "./ckpts/hunyuan-video-1.5/transformer/720p_t2v/diffusion_pytorch_model.safetensors"
vae_path = "./ckpts/hunyuan-video-1.5/vae/pytorch_model.pt"
text_encoder_path = "./ckpts/text_encoder/qwen_2.5_vl_7b.safetensors"
byt5_path = "./ckpts/text_encoder/byt5_model.safetensors"
image_encoder_path = "./ckpts/hunyuan-video-1.5/sigclip_vision_patch14_384.safetensors"
fp8_vl = false
fp8_scaled = true
vae_sample_size = 128
vae_enable_patch_conv = false
resume_path = ""
network_weights = ""
base_weights = ""
base_weights_multiplier = "1.0"
max_train_steps = ""
max_train_epochs = 20
gradient_checkpointing = true
gradient_checkpointing_cpu_offload = false
gradient_accumulation_steps = 1
guidance_scale = 6.0
seed = 1026
timestep_sampling = "sigmoid"
discrete_flow_shift = 7.0
sigmoid_scale = 1.0
weighting_scheme = ""
logit_mean = 0.0
logit_std = 1.0
mode_scale = 1.29
min_timestep = 0
max_timestep = 1000
show_timesteps = ""
learning_rate = "2e-4"
lr_scheduler = "cosine_with_min_lr"
lr_warmup_steps = 0
lr_decay_steps = 0.2
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_scheduler_timescale = 0
lr_scheduler_min_lr_ratio = 0.1
network_dim = 32
network_alpha = 16
network_dropout = 0
dim_from_weights = false
scale_weight_norms = 0
attn_mode = "flash"
split_attn = true
mixed_precision = "bf16"
full_bf16 = false
compile = true
compile_backend = "inductor"
compile_mode = "max-autotune-no-cudagraphs"
compile_fullgraph = false
compile_dynamic = "auto"
compile_cache_size_limit = 32
cuda_allow_tf32 = true
cuda_cudnn_benchmark = true
vae_dtype = ""
fp8_base = true
max_data_loader_n_workers = 8
persistent_workers = true
blocks_to_swap = 0
use_pinned_memory = true
optimizer_type = "AdamW_adv"
max_grad_norm = 1.0
d_coef = "0.5"
d0 = "1e-4"
wandb_api_key = ""
output_name = "hv_1_5_lora_qinglong"
save_every_n_epochs = "2"
save_every_n_steps = ""
save_last_n_epochs = ""
save_last_n_steps = ""
save_state = false
save_state_on_train_end = false
save_last_n_epochs_state = ""
save_last_n_steps_state = ""
enable_lycoris = false
lycoris_conv_dim = 0
lycoris_conv_alpha = 0
lycoris_algo = "lokr"
lycoris_dropout = 0
lycoris_preset = "attn-mlp"
lycoris_factor = 8
lycoris_decompose_both = false
lycoris_block_size = 4
lycoris_use_tucker = false
lycoris_use_scalar = false
lycoris_train_norm = false
lycoris_dora_wd = true
lycoris_full_matrix = false
lycoris_bypass_mode = false
lycoris_rescaled = 1
lycoris_constrain = false
enable_sample = false
sample_at_first = 1
sample_prompts = "./toml/qinglong_hv_1_5.txt"
sample_every_n_epochs = 1
sample_every_n_steps = 0
training_comment = "this LoRA model created by bdsqlsz'script"
metadata_title = ""
metadata_author = ""
metadata_description = ""
metadata_license = ""
metadata_tags = ""
async_upload = false
huggingface_repo_id = ""
huggingface_repo_type = ""
huggingface_path_in_repo = ""
huggingface_token = ""
huggingface_repo_visibility = ""
save_state_to_huggingface = false
resume_from_huggingface = false
multi_gpu = false
ddp_timeout = 120
ddp_gradient_as_bucket_view = 1
ddp_static_graph = 1
