arch = "Qwen Image"
_label = "Qwen Image 微调"
_source_script = "3.5.1qwen_image_train_db.ps1"
train_mode = "finetune"
dataset_config = "./toml/qinglong-qwen-image-datasets.toml"
dit_path = "./ckpts/diffusion_models/qwen_image_bf16.safetensors"
vae_path = "./ckpts/vae/qwen_image_vae.safetensors"
text_encoder_path = "./ckpts/text_encoder/qwen_2.5_vl_7b.safetensors"
fp8_vl = false
edit_mode = false
edit_plus = false
num_layers = ""
resume_path = ""
max_train_steps = ""
max_train_epochs = 40
gradient_checkpointing = true
gradient_checkpointing_cpu_offload = false
gradient_accumulation_steps = 1
guidance_scale = 1.0
seed = 1026
timestep_sampling = "qwen_shift"
discrete_flow_shift = 3.0
sigmoid_scale = 1.0
weighting_scheme = ""
logit_mean = -6.0
logit_std = 2.0
mode_scale = 1.29
min_timestep = 0
max_timestep = 1000
show_timesteps = ""
learning_rate = "1e-5"
lr_scheduler = "warmup_stable_decay"
lr_warmup_steps = 0
lr_decay_steps = 0.2
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_scheduler_timescale = 0
lr_scheduler_min_lr_ratio = 0.1
attn_mode = "flash"
split_attn = true
mixed_precision = "bf16"
full_bf16 = false
fused_backward_pass = false
mem_eff_save = false
compile = true
compile_backend = "inductor"
compile_mode = "reduce-overhead"
compile_fullgraph = true
compile_dynamic = "auto"
compile_cache_size_limit = 32
cuda_allow_tf32 = true
cuda_cudnn_benchmark = true
vae_dtype = ""
fp8_base = false
fp8_scaled = false
max_data_loader_n_workers = 8
persistent_workers = true
blocks_to_swap = 16
use_pinned_memory = true
img_in_txt_in_offloading = true
optimizer_type = "adafactor"
max_grad_norm = 1.0
d_coef = "0.5"
d0 = "1e-5"
wandb_api_key = ""
output_name = "qwen_image_db_qinglong"
save_every_n_epochs = "2"
save_every_n_steps = ""
save_last_n_epochs = ""
save_last_n_steps = ""
save_state = false
save_state_on_train_end = false
save_last_n_epochs_state = ""
save_last_n_steps_state = ""
enable_sample = true
sample_at_first = 0
sample_prompts = "./toml/qinglong_qwen_image.txt"
sample_every_n_epochs = 2
sample_every_n_steps = 0
training_comment = ""
metadata_title = ""
metadata_author = ""
metadata_description = ""
metadata_license = ""
metadata_tags = ""
async_upload = false
huggingface_repo_id = ""
huggingface_repo_type = ""
huggingface_path_in_repo = ""
huggingface_token = ""
huggingface_repo_visibility = ""
save_state_to_huggingface = false
resume_from_huggingface = false
multi_gpu = false
ddp_timeout = 120
ddp_gradient_as_bucket_view = 1
ddp_static_graph = 1
