[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false
num_repeats = 1

[[datasets]]
image_directory = "./train/minimax_h3_image_inbetween/images"
control_directory = "./train/minimax_h3_image_inbetween/control"
cache_directory = "./train/minimax_h3_image_inbetween/cache"
fp_1f_clean_indices = [0, 48]
fp_1f_target_index = 24
