arch = "FLUX.2"
_source_script = "5.9、flux2_generate.ps1"
dit_path = "./ckpts/diffusion_models/flux2-dev.safetensors"
vae_path = "./ckpts/vae/ae.safetensors"
version = "dev"
text_encoder_path = "./ckpts/text_encoder/mistral3_model.safetensors"
fp8_text_encoder = false
lora_weight = ""
lora_multiplier = "1.0"
include_patterns = ""
exclude_patterns = ""
save_merged_model = false
prompt = "A beautiful anime girl with long silver hair, blue eyes, wearing a white dress, masterpiece, best quality"
negative_prompt = ""
from_file = ""
video_size = "1024 1024"
infer_steps = 50
save_path = "./output_dir"
seed = 1026
guidance_scale = 4.0
embedded_cfg_scale = 4.0
control_image_path = ""
no_resize_control = false
fp8_base = false
fp8_scaled = true
device = ""
attn_mode = "sageattn"
blocks_to_swap = 0
use_pinned_memory_for_block_swap = true
output_type = "images"
no_metadata = false
latent_path = ""
lycoris = false
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = true
compile_cache_size_limit = 32
enable_tf32 = true
