_label = "HiDream O1 Dev Edit Flow I2I"
arch = "HiDream O1"
_source_script = "native_gui"
version = "dev"
dit_path = "./ckpts/hidream-o1-image-dev/hidream_o1_image_dev_2604_bf16.safetensors"
lora_weight = ""
lora_multiplier = "1.0"
include_patterns = ""
exclude_patterns = ""
save_merged_model = false
prompt = "edit the reference image with cinematic lighting"
negative_prompt = ""
from_file = ""
video_size = "2048 2048"
infer_steps = 28
save_path = "./output_dir/hidream_o1_dev_edit_flow.png"
seed = 1026
guidance_scale = 0.0
flow_shift = 1.0
dtype = "bfloat16"
editing_scheduler = "flow_match"
ref_images = ""
layout_bboxes = ""
keep_original_aspect = true
fp8_base = false
fp8_scaled = false
device = ""
attn_mode = "flash"
blocks_to_swap = 8
use_pinned_memory = true
output_type = "images"
no_metadata = false
latent_path = ""
lycoris = false
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = true
compile_cache_size_limit = 32
enable_tf32 = true
