_label = "HiDream O1 Generate"
arch = "HiDream O1"
_source_script = "native_gui"
version = "full"
dit_path = "./ckpts/hidream-o1-image"
text_encoder_path = "./ckpts/hidream-o1-image"
lora_weight = ""
lora_multiplier = "1.0"
include_patterns = ""
exclude_patterns = ""
save_merged_model = false
prompt = "a cinematic portrait of a woman in a red coat"
negative_prompt = ""
from_file = ""
video_size = "2048 2048"
infer_steps = 50
save_path = "./output_dir/hidream_o1.png"
seed = 1026
guidance_scale = 5.0
flow_shift = 3.0
dtype = "bfloat16"
noise_scale_start = 7.5
noise_scale_end = 7.5
noise_clip_std = 2.5
ref_images = ""
keep_original_aspect = false
fp8_base = false
fp8_scaled = false
device = ""
attn_mode = "flash"
blocks_to_swap = 24
use_pinned_memory = true
output_type = "images"
no_metadata = false
latent_path = ""
lycoris = false
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = true
compile_cache_size_limit = 32
enable_tf32 = true
