arch = "HunyuanVideo"
_source_script = "5.1hy_generate.ps1"
dit_path = "./ckpts/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt"
vae_path = "./ckpts/hunyuan-video-t2v-720p/vae/pytorch_model.pt"
vae_dtype = ""
te1_path = "./ckpts/text_encoder/llava_llama3_fp16.safetensors"
te2_path = "./ckpts/text_encoder_2/clip_l.safetensors"
vae_chunk_size = 32
vae_spatial_tile_sample_min_size = 128
embedded_cfg_scale = 7.0
fp8_t5 = false
fp8_scaled = true
negative_prompt = ""
guidance_scale = 5.0
vae_cache_cpu = true
exclude_patterns = ""
include_patterns = ""
lora_weight = "./output_dir/qinglong-000016.safetensors"
lora_multiplier = "1.0"
save_merged_model = false
prompt = "\"\"\"a girl with long green hair and deer ears, complete with deer antlers and a mini crown tilted on her head, strikes a confident pose against a simple black background. Her heterochromatic eyes, one blue and one yellow, gaze directly at the viewer as she holds one hand up and places the other on her hip. She is dressed in a green skirt and a matching crop top adorned with a green bow and brooch, featuring a blue gemstone. Her attire includes puffy detached short sleeves with lace gloves that are fingerless, and a green choker around her neck. A yellow flower and hair ornament decorate her hair, which falls between her eyes, and she wears a yellow rose above her ear. Her bare shoulders and midriff are exposed, showcasing her medium breasts, and she completes her look with black gloves and a virtual YouTuber aesthetic."
infer_steps = 20
save_path = "./output_dir/output.mp4"
seed = 1026
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = "auto"
compile_cache_size_limit = 32
enable_tf32 = true
flow_shift = 14.5
fp8_base = true
device = ""
attn_mode = "sageattn"
blocks_to_swap = 16
output_type = "both"
no_metadata = false
latent_path = ""
lycoris = false
