arch = "HV 1.5"
_source_script = "5.6hv_1_5_generate.ps1"
dit_path = "./ckpts/hunyuan-video-1.5/transformer/720p_t2v/diffusion_pytorch_model.safetensors"
vae_path = "./ckpts/hunyuan-video-1.5/vae/pytorch_model.pt"
vae_dtype = ""
text_encoder_path = "./ckpts/text_encoder/qwen_2.5_vl_7b.safetensors"
text_encoder_cpu = false
byt5_path = "./ckpts/text_encoder/byt5_model.safetensors"
image_encoder_path = "./ckpts/hunyuan-video-1.5/sigclip_vision_patch14_384.safetensors"
vae_sample_size = 128
vae_enable_patch_conv = false
lora_weight = ""
lora_multiplier = "1.0"
save_merged_model = false
prompt = "A beautiful landscape with mountains and a lake, cinematic quality, 4K"
negative_prompt = ""
from_file = ""
infer_steps = 50
save_path = "./output_dir"
seed = 1026
guidance_scale = 6.0
flow_shift = 7.0
fp8_base = true
fp8_scaled = true
device = ""
attn_mode = "sageattn"
blocks_to_swap = 0
use_pinned_memory_for_block_swap = true
output_type = "video"
no_metadata = false
latent_path = ""
lycoris = false
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = true
compile_cache_size_limit = 32
enable_tf32 = true
