_label = "Krea-2 T2I"
arch = "Krea-2"
_source_script = "native_gui"
version = "raw"
dit_path = "./ckpts/diffusion_models/krea2_raw_bf16.safetensors"
vae_path = "./ckpts/vae/qwen_image_vae.safetensors"
text_encoder_path = "./ckpts/text_encoder/qwen_3_VL_4b.safetensors"
fp8_scaled = false
split_attn = false
text_encoder_cpu = false
turbo = false
lora_weight = ""
lora_multiplier = "1.0"
prompt = "A beautiful anime girl with long silver hair, blue eyes, wearing a white dress, masterpiece, best quality"
negative_prompt = ""
from_file = ""
video_size = "1024 1024"
infer_steps = 28
guidance_scale = 5.5
mu = ""
y1 = ""
y2 = ""
num_images = 1
save_path = "./output_dir/krea2"
seed = 1026
device = ""
attn_mode = "flash"
blocks_to_swap = 0
use_pinned_memory = true
enable_tf32 = true
