_label = "Lens T2I"
arch = "Lens"
_source_script = "native_gui"
version = "lens_bf16"
dit_path = "./ckpts/lens/diffusion_models/lens_bf16.safetensors"
vae_path = "./ckpts/lens/vae/flux2-vae.safetensors"
text_encoder_path = "./ckpts/lens/text_encoders/gpt_oss_20b_nvfp4.safetensors"
prompt = "A detailed portrait of a girl with long green hair, deer ears, and a small crown, studio lighting, high quality"
negative_prompt = ""
video_size = "1024 1024"
infer_steps = 20
save_path = "./output_dir/lens.png"
seed = 1026
guidance_scale = 5.0
device = ""
dit_dtype = "bfloat16"
vae_dtype = "float32"
text_encoder_dtype = "bfloat16"
disable_numpy_memmap = false
no_metadata = false
