arch = "Long-CAT"
_source_script = "5.7long_cat_generate.ps1"
dit_path = "./ckpts/diffusion_models/longcat_dit.safetensors"
vae_path = "./ckpts/vae/qwen_image_vae.safetensors"
vae_dtype = ""
te1_path = "./ckpts/text_encoder/t5xxl_fp16.safetensors"
te2_path = "./ckpts/text_encoder_2/clip_l.safetensors"
vae_chunk_size = 32
vae_spatial_tile_sample_min_size = 128
embedded_cfg_scale = 2.5
fp8_t5 = false
negative_prompt = "low quality, bad anatomy"
guidance_scale = 4.0
vae_cache_cpu = true
exclude_patterns = ""
include_patterns = ""
offload_inactive_dit = false
image_encoder_path = "./ckpts/framepack/sigclip_vision_patch14_384.safetensors"
no_resize_control = false
text_encoder_vl_path = "./ckpts/text_encoder/qwen_2.5_vl_7b.safetensors"
text_encoder_cpu = false
edit_mode = false
edit_plus = false
control_image_path = ""
lora_weight = "./output_dir/qinglong_figure.safetensors"
lora_multiplier = "1.0"
save_merged_model = false
prompt = "transform character to PVC figure with simple background."
from_file = ""
infer_steps = 25
save_path = "./output_dir"
seed = 1026
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = "auto"
compile_cache_size_limit = 32
enable_tf32 = true
flow_shift = 2.0
fp8_base = true
fp8_scaled = true
device = ""
attn_mode = "sageattn"
blocks_to_swap = 8
output_type = "video"
no_metadata = false
latent_path = ""
lycoris = false
