arch = "Wan2.1"
_source_script = "5.2、wan_generate.ps1"
dit_path = "./ckpts/wan/split_files/diffusion_models/wan2.1_t2v_14B_fp16.safetensors"
dit_high_noise = "./ckpts/wan/split_files/diffusion_models/wan2.1_t2v_14B_fp16.safetensors"
vae_path = "./ckpts/vae/Wan2.1_VAE.pth"
vae_dtype = ""
te1_path = "./ckpts/text_encoder/llava_llama3_fp16.safetensors"
te2_path = "./ckpts/text_encoder_2/clip_l.safetensors"
vae_chunk_size = 32
vae_spatial_tile_sample_min_size = 128
embedded_cfg_scale = 7.0
t5_path = "./ckpts/text_encoder/models_t5_umt5-xxl-enc-bf16.pth"
fp8_t5 = false
negative_prompt = ""
guidance_scale = 5.0
vae_cache_cpu = true
exclude_patterns = ""
include_patterns = ""
offload_inactive_dit = false
control_image_path = ""
image_encoder_path = "./ckpts/framepack/sigclip_vision_patch14_384.safetensors"
no_resize_control = false
lora_weight = "./output_dir/wan_qinglong.safetensors"
lora_multiplier = "1.0"
save_merged_model = false
prompt = "\"\"\"1girl, solo, long hair, looking at viewer blue eyes, hair ornament, animal ears, hair between eyes, bare shoulders, medium breasts, yellow eyes, short sleeves, :d, detached sleeves, green hair, black gloves, virtual youtuber, puffy sleeves, midriff, hair flower, fingerless gloves, crop top, puffy short sleeves, fake animal ears,gem, green skirt, brooch, green bow, yellow flower, green shirt, mini crown, tilted headwear,and the girl undergoes a r0t4tion 360 degrees rotation"
infer_steps = 20
save_path = "./output_dir/output.mp4"
seed = 1026
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = "auto"
compile_cache_size_limit = 32
enable_tf32 = true
flow_shift = 3.0
fp8_base = true
fp8_scaled = true
device = ""
attn_mode = "sageattn"
blocks_to_swap = 8
output_type = "both"
no_metadata = false
latent_path = ""
lycoris = false
