arch = "Z-Image"
_source_script = "5.8、zimage_generate.ps1"
version = "base"
dit_path = "./ckpts/diffusion_models/z_image_bf16.safetensors"
vae_path = "./ckpts/vae/ae.safetensors"
text_encoder_path = "./ckpts/text_encoder/qwen_3_4b.safetensors"
text_encoder_cpu = false
lora_weight = ""
lora_multiplier = "1.0"
include_patterns = ""
exclude_patterns = ""
save_merged_model = false
prompt = "A beautiful anime girl with long silver hair, blue eyes, wearing a white dress, masterpiece, best quality"
negative_prompt = ""
from_file = ""
video_size = "1024 1024"
infer_steps = 25
save_path = "./output_dir"
seed = 1026
guidance_scale = 0.0
embedded_cfg_scale = 2.5
flow_shift = 3.0
fp8_base = true
fp8_scaled = true
device = ""
attn_mode = "sageattn"
blocks_to_swap = 0
use_pinned_memory_for_block_swap = true
output_type = "images"
no_metadata = false
latent_path = ""
lycoris = false
compile = false
compile_backend = "inductor"
compile_mode = "default"
compile_fullgraph = false
compile_dynamic = true
compile_cache_size_limit = 32
enable_tf32 = true
